E3SM-Project/e3sm_to_cmip

e3sm_to_cmip/lib.py
e3sm_to_cmip/util.py

This PR fixes 2 bugs:
* When atm variables are requested by MPAS handlers, they are now processed by `find_atm_files` rather than raising an exception
* Fixes a bug in parallel mode of trying to iterate over a handler
closes #13

Fix bugs in parallel mode and in passing atm variable so MPAS handlers

---

e3sm_to_cmip/mpas.py

Use the standard NetCDF4 fill value, not the cmor default of 1e20, which is too close to reasonable ocean values for certain fields.

Fix fill value

---

e3sm_to_cmip/cmor_handlers/masscello.py
e3sm_to_cmip/mpas.py

Masking before remapping now sets invalid cells to zero mass, rather than a fill value.  After remapping, fill values from ncremap (indicating cells on the destination grid that are empty in the MPAS mesh) are replaced with zeros.

Fix masscello masking

---

e3sm_to_cmip/mpas.py

This could be used instead of the `-d2f` flag to `ncremap`, which seems to be causing trouble.

Convert float64 to float32 in mpas.write_cmor

---

e3sm_to_cmip/mpas.py

This replaces fill values with NaNs, which is the behavior we want for subsequent masking.
This should fix the sea-ice masking issue we've been seeing.

After remap, use xarray masking

---

conda/conda_build.sh
conda/meta.yaml

There is no need for separate builds for different python versions and E3SM-Unified is now using python 3.8 by default, and supports python 3.7-3.9.
Bumped the build number to 2.

Make conda recipe noarch: python

---

README.md
conda/dev.yml

This PR adds a conda development environment for the repo so that developer doesn't have to manually specify the dependencies. The versions are pinned in order to keep the dev environment reproducible and predictable.

Add conda development environment to simplify setup

---

README.md
conda/dev.yml

- Closes #79 
This PR adds the remaining development environment dependencies, including:
- `cdutil`
- `cdms2`,
- `cwl`
- `nodejs`

Add cdutil, cdms2, cwl, and nodejs to dev env

---

e3sm_to_cmip/cmor_handlers/pr_highfreq.py
e3sm_to_cmip/cmor_handlers/rlut_highfreq.py
e3sm_to_cmip/resources/default_handler_info.yaml
scripts/cwl_workflows/atm-highfreq/discover_atm_files.cwl
scripts/cwl_workflows/atm-highfreq/find_start_end.cwl

Summary of Changes
* Update logic in `get_year()` in `find_start_end.cwl` to parse the correct regex pattern for years (monthly and sub-monthly)
* Update `discover_atm_files` to parse the correct files for their absolute paths to return `atm_files` list
* Revert changes related to https://github.com/E3SM-Project/e3sm_to_cmip/commit/b54dea7af29202fab6f2b5895fa69e7b7c31aca2#diff-9cc8b4180a30ce9a2a9dd6676bc74fd450b01f055d677e3a59005c305bea0bd7
*  `pr_highfreq` should not be defined as default handler because it is not listed in `CMIP6_day.json`. 
* Remove `rlut_highfreq` from `default_handler_info.yaml` and add `rlut_highfreq.py`, which is based on `rlut.py` with some minor tweaks

PR #83 Fix high freq cwl (review fixes)

---

e3sm_to_cmip/cmor_handlers/pr_highfreq.py
e3sm_to_cmip/cmor_handlers/rlut_highfreq.py
e3sm_to_cmip/resources/default_handler_info.yaml
scripts/cwl_workflows/atm-highfreq/atm-highfreq.cwl
scripts/cwl_workflows/atm-highfreq/discover_atm_files.cwl
scripts/cwl_workflows/atm-highfreq/find_start_end.cwl

I _think_ this will fix the issue with the high frequency time gaps, however since I dont have access to any data I havent been able to test it. There's a 10 year chunk of testing data setup under `/p/user_pub/e3sm/baldwin32/warehouse_testing/E3SM/test/test/test/atmos/native/model-output/day/ens1/v0/` to test this change, create a new directory, and paste this into a file named atm-highfreq-job.yaml
```
data_path: /p/user_pub/e3sm/baldwin32/warehouse_testing/E3SM/test/test/test/atmos/native/model-output/day/ens1/v0/
frequency: 2
sample_freq: day
time_steps_per_day: '1'
num_workers: 12
account: e3sm
partition: debug
timeout: 2:00:00
hrz_atm_map_path: /home/zender1/data/maps/map_ne30np4_to_cmip6_180x360_aave.20181001.nc
tables_path: /home/baldwin32/projects/cmip6-cmor-tables/Tables/ …
```

attempt to fix highfreq issue

---

e3sm_to_cmip/cmor_handlers/rlut_highfreq.py

This PR fixes time invariant daily rlut (i.e., files in /p/user_pub/work/CMIP6/CMIP/E3SM-Project/E3SM-1-0/historical/r1i1p1f1/day/rlut/gr/v20210910). 
An example output can be found on acme1:/p/user_pub/e3sm/zhang40/tests/rlut_day_E3SM-1-0_historical_r1i1p1f1_gr_18500101-18591231.nc
All daily rlut files need to be republished.

fix time invariant daily rlut

---

e3sm_to_cmip/default.py

@TonyB9000 reported that in newer version of cmorized data, “Not-a-Number (float)” are presented as ‘NaNf’, while old version has `-` for missing values. Example:
>> Old version:
>> 
>>       _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
>> _, _, _,
>> 
>>       _, _, _, 2.037439e-05, 2.300697e-05, 2.66528e-05, _, _, _, _,
>> _, _, _, _,
>> 
>>       _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
>> _, _, _,
>> 
>> New Version:
>> 
>>       NaNf, NaNf, NaNf, NaNf, NaNf, NaNf, NaNf, NaNf, NaNf, NaNf,
>> NaNf, NaNf,
>> 
>>       NaNf, NaNf, NaNf, NaNf, 2.037439e-08, 2.300698e-08,
>> 2.665283e-08, NaNf,
>> 
>>       NaNf, NaNf, NaNf, NaNf, NaNf, NaNf, NaNf, NaNf, NaNf, NaNf,
>> NaNf, NaNf,
>> 
>> Why are “Not-a-Number (float)” presented as ‘_’ for one file, …

Avoid NaNf as missing value

---

e3sm_to_cmip/cmor_handlers/cLitter.py
e3sm_to_cmip/cmor_handlers/lai.py
e3sm_to_cmip/cmor_handlers/mrfso.py
e3sm_to_cmip/cmor_handlers/mrso.py
e3sm_to_cmip/cmor_handlers/tran.py
e3sm_to_cmip/cmor_handlers/tsl.py

- Closes #107 
Adds fill value for land variable handlers 1-12 in this list: https://acme-climate.atlassian.net/wiki/spaces/DOC/pages/925500501/Lmon+variable+conversion+table
Land variables fixed
1. `cLitter`
2. `lai`
3. `mrfso`
4. `mrso`
5. `tran`
6. `tsl`
Default land vars already fixed (through `default.py`):
1. `mrsos`
2. `mrros`
3. `mrro`
4. `prveg`
5. `evspsblveg`
6. `evspsblsoi`

Access land var xarray objects using `.values` and fix `NaNf`

---

.github/workflows/build_workflow.yml
.github/workflows/release_workflow.yml
conda-env/ci.yml
conda-env/dev.yml

- Closes #116 
Additional Info
- `ci.yml` requires the same base dependencies specified in the conda-forge feedstock when building the local package using `pip` for testing in the CI/CD build workflow
- Update sphinx versions in workflows

Update dependencies in `ci.yml` and `dev.yml`

---

docs/source/examples.rst
e3sm_to_cmip/__main__.py
e3sm_to_cmip/util.py

I believe this clarifies and improves the help text.  There is still future work involving the parsing logic.  Specifically, "--info" will fail if "--map" is not specified (for mpas* realm), but map is not needed.  You can supply "--map stub" and it works fine.

Clarified and expanded E2C help text

---

e3sm_to_cmip/util.py

There was a a drop in the codecov from the latest `master` commit (https://codecov.io/gh/E3SM-Project/e3sm_to_cmip/commit/e6e0a014357c47f854f81fb75820fe3cdb980a03/).

Fix codecov report

---

.github/workflows/build_workflow.yml

This keeps the `master` codecov report up to date
- Closes #145

Run CI/CD on "push" and "workflow_dispatch"

---

scripts/cwl_workflows/atm-mon-model-lev/atm-std.cwl
scripts/cwl_workflows/atm-mon-model-lev/cmor.cwl
scripts/cwl_workflows/atm-mon-plev/atm-plev.cwl
scripts/cwl_workflows/atm-mon-plev/cmor.cwl
scripts/cwl_workflows/atm-unified-eam/atm-unified.cwl
scripts/cwl_workflows/atm-unified-eam/cmor.cwl
scripts/cwl_workflows/atm-unified/atm-unified.cwl
scripts/cwl_workflows/atm-unified/cmor.cwl
scripts/cwl_workflows/lnd-elm/cmor.cwl
scripts/cwl_workflows/lnd-elm/lnd.cwl
scripts/cwl_workflows/lnd-n2n/cmor.cwl
scripts/cwl_workflows/lnd-n2n/lnd.cwl
scripts/cwl_workflows/mpaso-atm/mpaso_sbatch_render.cwl
scripts/cwl_workflows/mpaso/mpaso.cwl
scripts/cwl_workflows/mpaso/mpaso_sbatch_render.cwl
scripts/cwl_workflows/mpassi/mpassi.cwl
scripts/cwl_workflows/mpassi/mpassi_cmor.cwl
scripts/cwl_workflows/mpassi/mpassi_srun_render_cmor.cwl

At Tom's suggestion, I removed all of the "commented-out" logging lines.  I believe Sterling had discovered problems with retrieving cwltool cmor logs, perhaps due to temp-file/directory issues, that would cause whole workflows to fail.  I also eliminated 4 instances of "--precheck" on the command lines, until we can ascertain how to make that functionality cognizant of variant-label.  Presently, the precheck would cause realization_index > 1 to fail, if realization_index 1 data were present, thinking that the data was already generated.

Elide cwl logging

---

e3sm_to_cmip/mpas.py

This PR bring back time as record dimension as in raw data before calling ncremap for mpas data regridding.
@TonyB9000 reported chunk size error when processing a 3d variable `zhalfo` with >2 years per chunk. Error message:
```
"nco_def_var_chunking(): ERROR Total requested chunk size = 6935055840
exceeds netCDF maximium-supported chunk size = 4294967295"
```
Notes from @czender: Cause of ncremap's "chunk size" error:
When processing ocean fields of roughly the same size as
we used in the v1 CMIP datasets, the new v2 workflow fails
when the ncremap regridder step throws a "chunk size" error.
This new occurs because the intermediate files that ncremap
is asked to regrid contain "time" as a fixed (not record) dimension.
"Time" is a record variable in the raw MPAS v2 data.
The property is …

Remain time as record dimension as raw data and include --no_permute 

---

.github/workflows/build_workflow.yml
.pre-commit-config.yaml
conda-env/ci.yml
conda-env/dev.yml
conda-env/readthedocs.yml
setup.cfg

This PR bumps conda env dependencies and replaces/removes unnecessary dependencies. It also adds some configuration for `mypy`.
This PR was driven from some dependency conflict issues with `nco` and `libzlib`, but routine housecleaning should be performed anyways.

Bump conda env dependencies

---

e3sm_to_cmip/lib.py

Looping over all atm variables, fix in commit 4f7a0a4 resulted "clw, cl, cli failed to complete". 
This PR adds a type check to ensure that `numpy.ndarray` can also be accommodated. It is worth to check why the axes objects have various type, but will not address in this PR

make fix in 4f7a0a4 work for other handlers

---

scripts/example_end-to-end_script.sh

Provide an end-to-end example script that is independent from CWL workflows.
This script serves for a few purpose:
- establish the data and script required by integration tests.
- provide necessary commands for interfacing with zppy, with the hope that zppy can create and archive intermediate files required as e3sm_to_cmip input. 
TO DO:

Add example script

---

e3sm_to_cmip/__main__.py

numpy.warnings alias was deprecated in newer versions for numpy and posed errors in e3sm-unified 1.9.0 rc testing.

Fix deprecated numpy.warnings

---

e3sm_to_cmip/cmor_handlers/utils.py
e3sm_to_cmip/mpas.py
tests/cmor_handlers/test_utils.py

- Close #202 
This PR updates the KeyError raised for missing handlers and non-derivable variables to logger warning. This allows e3sm_to_cmip to continue processing variables that do have defined handlers or can be derived rather than breaking the run, which is how `e3sm_to_cmip <= 1.9.1` behaved.

Update KeyError raised for missing handlers or non-derivable variables to logger warning

---

conda-env/ci.yml
conda-env/dev.yml
e3sm_to_cmip/cmor_handlers/handler.py

- Closes #227 
This PR updates the `VarHandler._get_mfdataset()` to use xCDAT to open the input datasets and adds bounds for lat and lon if they are missing.
```python
from e3sm_to_cmip.__main__ import E3SMtoCMIP
args = [
"--var-list",
"lai",
"--input",
"/lcrc/group/e3sm/ac.zhang40/tests/20231012.v3alpha04_trigrid_bgc.piControl.chrysalis/post/lnd/native/ts/monthly/50yr",
"--output",
"./",
"--tables-path",
"/lcrc/group/e3sm/public_html/diagnostics/e3sm_to_cmip_data/cmip6-cmor-tables/Tables/",
"--user-metadata",
"/lcrc/group/e3sm/public_html/diagnostics/e3sm_to_cmip_data/user_metadata.json",
"--serial",
]
run = E3SMtoCMIP(args)
run.run()
```
```python
2023-11-27 22:34:27,673 [INFO]: __main__.py(__init__:142) >> --------------------------------------
2023-11-27 22:34:27,673 [INFO]: …
```

Add lat and lon bounds if missing in input datasets

---

e3sm_to_cmip/cmor_handlers/utils.py

- Closes #195 
`imp` is breaking conda-forge from building e3sm_to_cmip (https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=839089&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3).

Replace `imp` with `importlib`

---

e3sm_to_cmip/cmor_handlers/handler.py
scripts/debug/549_zppy_debug/549_zppy_ts.py

By explicitly closing the multi-file `xr.Dataset` object, we avoid any possibility of resource locking with `.nc` files
This is an attempted fix for https://github.com/E3SM-Project/zppy/issues/549.
If applicable:

Explicitly close `xr.Dataset` in `VarHandler.cmorize()`

---

e3sm_to_cmip/__init__.py
e3sm_to_cmip/cmor_handlers/handler.py
tbump.toml

Bump to v1.11.2rc2 

---

e3sm_to_cmip/mpas.py

- This is an attempt to avoid `to_netcdf()` hanging. Refer to "Related Info" section below for more info.
If applicable:
Related lines of code -- notice how the dask config is set to threads.
https://github.com/E3SM-Project/e3sm_to_cmip/blob/56b2d40b928f7f6fdc59ef6709813bfc05ba862b/e3sm_to_cmip/mpas.py#L306-L325
From @TonyB9000 email, 3/13/24 at 1:07PM: 
Hangs here:
```python
2024-03-12 23:46:18,545 [INFO]: siv.py(handle:48) >> Starting siv
2024-03-12 23:46:18,545 [INFO]: siv.py(handle:48) >> Starting siv
2024-03-12 23:46:18,545_545:INFO:handle:Starting siv
2024-03-12 23:47:29,946 [INFO]: siv.py(handle:72) >> Calling mpas.remap for siv
2024-03-12 23:47:29,946 [INFO]: siv.py(handle:72) >> Calling mpas.remap for siv
2024-03-12 23:47:29,946_946:INFO:handle:Calling mpas.remap for siv …
```

Update `mpas.open_mfdataset()` to use `lock=False`

---

scripts/example_end_to_end_script.sh

Changed area to areacella in fx var list, and corrected missing comma in Omon var list in the example_end_to_end script".
- Closes #<ISSUE_NUMBER_HERE>
If applicable:

Fix `example_end_to_end_script` -- changed `area` to `areacella` and added missing comma

---

e3sm_to_cmip/mpas.py

Previously, the `write_netcdf()` function was trying to add a `_FillValue` attribute to variables even if they already had one. With this change, we skip variables that already have a fill value defined
- Closes #<ISSUE_NUMBER_HERE>
If applicable:

Fix redundant `_FillValue` attribute for MPAS fields

---

e3sm_to_cmip/cmor_handlers/vars/areacella.py
e3sm_to_cmip/cmor_handlers/vars/clisccp.py
e3sm_to_cmip/cmor_handlers/vars/orog.py
e3sm_to_cmip/cmor_handlers/vars/sftlf.py

This re-addresses issue #273.
When separating the cmor consolidation material from the logging redesign, I neglected to include the four variable handlers still listed under "vars" (areacella.py, clisccp.py, orog.py, and sftlf.py).  Rather than re-open that branch, I created this one.

Additional refactoring of cmor setup for specific variables (`areacella`, `clisccp`, `orog`, `sftlf`)

---

.github/workflows/build_workflow.yml

Hello! I am making this PR to bring in a few CI changes @xylar and I have been implementing across other repos. These changes include:
1. `cancel_others` is now set to false by default, which should make it easier to decipher if a bug is isolated to a specific version of python via CI
2. All references to `mamba`/`Mambaforge` have been removed and/or changed to `conda` and `Miniforge3`
3. The timeout for the `pre-commit` job has been upped to 5 minutes (we were having jobs occasionally run out of time during the caching step)
For the `pre-commit` change, I just upped the number in the comment where the current `pre-commit` settings are listed, but I didn't un-comment anything.
If applicable:

Tweak behaviours of build workflow

---

e3sm_to_cmip/mpas.py

We have discovered that 3D ocean variables have not been correctly masked following https://github.com/E3SM-Project/e3sm_to_cmip/pull/155.  The review of that PR focused entirely on correctly masking sea-ice output and we missed the impact it had on 3D ocean variables, which was that is removed manual masking after remapping and assumed (incorrectly) that ncremap was handling the masking and renormaliztion itself.  Instead, the 3D fields were being set to zero (not the `_FillValue`) below bathymetry, leading to fractional values after remapping, as reported in https://github.com/E3SM-Project/E3SM/discussions/6546
If applicable:

Fix masking of 3D MPAS-Ocean variables

---

e3sm_to_cmip/cmor_handlers/_formulas.py
e3sm_to_cmip/cmor_handlers/handlers.yaml

Add aerosol species mixing ratio, inlcuding:
mmrbc, mmroa, mmrsoa, mmrdust, mmrss, mmrso4

add 3D aerosol species mixing ratio

---

e3sm_to_cmip/__init__.py
tbump.toml

Bump to 1.12.2

---

e3sm_to_cmip/cmor_handlers/handler.py
e3sm_to_cmip/cmor_handlers/mpas_vars/pbo.py
e3sm_to_cmip/cmor_handlers/mpas_vars/pso.py
e3sm_to_cmip/mpas.py

Related to https://github.com/E3SM-Project/e3sm_to_cmip/pull/307#issuecomment-3357451239
If applicable:

Preserve legacy Xarray `compat` and `join` settings
