- cmor_handlers/rlus.py
- cmor_handlers/rsus.py
> Update some handle docstrings to reflect transform

- e3sm_to_cmip/cmor_handlers/mlotst.py
Switching from temperature to density threshold
@vanroekel wrote:
> We do not actually have the variable requested.  It is a density criterion based on a surface threshold of 0.125, we have a 10m threshold at 0.03.  using dThreshMLD might be close
> Fix mlotst handler

- e3sm_to_cmip/cmor_handlers/masso.py
- e3sm_to_cmip/cmor_handlers/volo.py
It isn't clear to me why this change fixes the rounding issue but it seems to.
> Fix masso and volo masking

- e3sm_to_cmip/cmor_handlers/sob.py
- e3sm_to_cmip/cmor_handlers/wfo.py
Default comments aren't very helpful
> Fix comments in sob and wfo handlers

- e3sm_to_cmip/cmor_handlers/wo.py
- e3sm_to_cmip/mpas.py
Put it on the z-mid grid instead of at layer interfaces
closes #16
> Fix wo handler

- scripts/dataset_spec.yaml
- scripts/generate_xmls_cmip6.py
Add a script to generate xml files for the cmip variables in preparation for post-processing and evaluation.
> Xml script

- scripts/README.md
- scripts/data_stager.py
The data stager downloads zstash tarballs and extract data data files that match specified components and files patterns. It also extracts a restart and namelist file, and create a manifest file. Then, it transfers the files to a specified Globus endpoint.
> Data stager

- e3sm_to_cmip/cmor_handlers/msftmz.py
Since MPAS-Ocean is volume- rather than mass-conserving, it make sense to use the reference density (rather than the full density) to convert from volume to mass transport.
> Multiply MOC by density to get right units

- e3sm_to_cmip/cmor_handlers/cesm_mmrbc.py
- e3sm_to_cmip/cmor_handlers/cesm_mmrso4.py
- e3sm_to_cmip/cmor_handlers/emibc.py
- e3sm_to_cmip/cmor_handlers/emiso2.py
- e3sm_to_cmip/cmor_handlers/emiso4.py
- e3sm_to_cmip/cmor_handlers/mmrbc.py
- e3sm_to_cmip/cmor_handlers/mmrso4.py
- e3sm_to_cmip/cmor_handlers/so2.py
- e3sm_to_cmip/resources/default_handler_info.yaml
- scripts/cwl_workflows/atm-cesm/append_bnds_nco_py.cwl
- scripts/cwl_workflows/atm-cesm/atm-cesm.cwl
- scripts/cwl_workflows/atm-cesm/atm-unified-job.yml
- scripts/cwl_workflows/atm-cesm/cmor.cwl
- scripts/cwl_workflows/atm-cesm/discover_atm_files.cwl
- scripts/cwl_workflows/atm-cesm/file_to_string_list.cwl
- scripts/cwl_workflows/atm-cesm/find_casename.cwl
- scripts/cwl_workflows/atm-cesm/find_start_end.cwl
- scripts/cwl_workflows/atm-cesm/generate_segments.cwl
- scripts/cwl_workflows/atm-cesm/hrzremap_posin.cwl
- scripts/cwl_workflows/atm-cesm/hrzremap_posin_paths.cwl
- scripts/cwl_workflows/atm-cesm/vrtremap.cwl
Here's all the changes (I think) made to the atm-unified workflows to work on CESM data. Thanks for all your help!
> atm_cesm workflow and new handlers

- e3sm_to_cmip/cmor_handlers/__init__.py
- e3sm_to_cmip/cmor_handlers/hur.py
- e3sm_to_cmip/cmor_handlers/hus.py
- e3sm_to_cmip/cmor_handlers/o3.py
- e3sm_to_cmip/cmor_handlers/ta.py
- e3sm_to_cmip/cmor_handlers/ua.py
- e3sm_to_cmip/cmor_handlers/va.py
- e3sm_to_cmip/cmor_handlers/wap.py
- e3sm_to_cmip/cmor_handlers/zg.py
- e3sm_to_cmip/default.py
- scripts/cwl_workflows/atm-unified/atm-unified.cwl
> Remove nan as fillvalue 3 d plev

- .github/workflows/build_workflow.yml
Continuation of PR #105 and PR #110
> Remove redundant `check-jobs-to-skip` job

- e3sm_to_cmip/util.py
> fix yaml load

- conda-env/dev.yml
I tested this environment this time, which I forgot to in #117.
> Fix incorrect xarray version in `dev.yml`

- conda-env/ci.yml
- conda-env/dev.yml
- Closes #122 
- Closes #123 
Summary of Changes
- Update Python version from `3.8.10` to `3.9.10` and move CWL deps to under Base section  in `dev.yml`
- Add `cmor` version constraint and add CWL deps to `ci.yml`
Acceptance Criteria
> Update `ci.yml` and `dev.yml`

- e3sm_to_cmip/__main__.py
- e3sm_to_cmip/_logger.py
- e3sm_to_cmip/util.py
Minor added logging.
@tomvothecoder : how/when can a "release" occur, and how do I obtain in datasm?  (Have I asked this question before?  Sorry.)
> Add e2c logging

- .pre-commit-config.yaml
- conda-env/dev.yml
- e3sm_to_cmip/__main__.py
- e3sm_to_cmip/_logger.py
- e3sm_to_cmip/cmor_handlers/siconc.py
- e3sm_to_cmip/cmor_handlers/simass.py
- e3sm_to_cmip/cmor_handlers/sisnmass.py
- e3sm_to_cmip/cmor_handlers/sisnthick.py
- e3sm_to_cmip/cmor_handlers/sitemptop.py
- e3sm_to_cmip/cmor_handlers/sithick.py
- e3sm_to_cmip/cmor_handlers/sitimefrac.py
- e3sm_to_cmip/cmor_handlers/siu.py
- e3sm_to_cmip/cmor_handlers/siv.py
- e3sm_to_cmip/default.py
- e3sm_to_cmip/lib.py
- e3sm_to_cmip/mpas.py
Using ncremap  -P mpasseaice for sgs mode. A new routine to slice time-series and conduct per time-slice regridding is required for applying ncremap's sgs mode for mpas seaice.
> Preps for v2 Part2 seaice

- e3sm_to_cmip/mpas.py
Changed pcode "mpaso" to "mpasocean", as it appears in the cmor handlers.
> fixed pcode for mpas in remap

- conda-env/dev.yml
- e3sm_to_cmip/__init__.py
- tbump.toml
Also update nco to 5.1.1 in dev env.
> Bump to 1.9.1

- conda-env/dev.yml
- e3sm_to_cmip/__init__.py
- tbump.toml
> Bump to 1.9.1rc1

- e3sm_to_cmip/__init__.py
- tbump.toml
> Bump to 1.9.0rc2

- e3sm_to_cmip/__init__.py
- tbump.toml
Reverts E3SM-Project/e3sm_to_cmip#166
> Revert "Bump to 1.9.0rc2"

- e3sm_to_cmip/__init__.py
- tbump.toml
> Bump to 1.9.1rc2

- e3sm_to_cmip/_logger.py
> Add `os.markdirs()` for `/logs` directory

- README.md
- e3sm_to_cmip/__init__.py
- tbump.toml
- Related to https://github.com/conda-forge/e3sm_to_cmip-feedstock/pull/27
> Bump to v1.10.0rc1

- e3sm_to_cmip/cmor_handlers/handlers.yaml
- e3sm_to_cmip/cmor_handlers/vars/sftlf.py
> Fix handling sftlf/LANDFRAC

- e3sm_to_cmip/__init__.py
- tbump.toml
> Bump to 1.10.0rc3

- e3sm_to_cmip/cmor_handlers/handler.py
- Closes #233 
Log output after fix:
```bash
2023-12-18 21:48:54,624 [INFO]: __main__.py(__init__:142) >> --------------------------------------
2023-12-18 21:48:54,624 [INFO]: __main__.py(__init__:142) >> --------------------------------------
2023-12-18 21:48:54,624_624:INFO:__init__:--------------------------------------
2023-12-18 21:48:54,626 [INFO]: __main__.py(__init__:143) >> | E3SM to CMIP Configuration
2023-12-18 21:48:54,626 [INFO]: __main__.py(__init__:143) >> | E3SM to CMIP Configuration
2023-12-18 21:48:54,626_626:INFO:__init__:| E3SM to CMIP Configuration
2023-12-18 21:48:54,627 [INFO]: __main__.py(__init__:144) >> --------------------------------------
2023-12-18 21:48:54,627 [INFO]: __main__.py(__init__:144) >> --------------------------------------
2023-12-18 …
```
> Fix segmentation fault due to early `cmor.close()` call

- e3sm_to_cmip/__init__.py
- tbump.toml
- Closes #<ISSUE_NUMBER_HERE>
If applicable:
> Bump to 1.11.2

- e3sm_to_cmip/mpas.py
> removed lock= setting from xarray.open_mfdataset in mpas.py

- .github/workflows/build_workflow.yml
- .pre-commit-config.yaml
- Use token for codecov
- Refactor to make `skip-duplicate-actions` its own job
- Add `build-result` job
- Fix all `pre-commit` errors
If applicable:
> Update build workflow

- e3sm_to_cmip/cmor_handlers/mpas_vars/hfsifrazil.py
This fixes the issue mentioned in https://github.com/E3SM-Project/e3sm_to_cmip/pull/270#issuecomment-2339303713
If applicable:
> Remove positive from hfsifrazil

- e3sm_to_cmip/__init__.py
- tbump.toml
- Closes #<ISSUE_NUMBER_HERE>
If applicable:
> Bump to v1.11.3

- docs/source/development-guide.rst
- tests/run_script.py
> Add generic run script for testing changes at runtime

- e3sm_to_cmip/runner.py
- scripts/debug/291-get-failures/mvce.py
> Fix conditional for logging successful cmor handlers

- e3sm_to_cmip/__init__.py
- tbump.toml
> Bump to v1.12.0

- e3sm_to_cmip/__init__.py
- tbump.toml
> Bump to v1.12.1

- .github/workflows/build_workflow.yml
- conda-env/ci.yml
- conda-env/dev.yml
- pyproject.toml
> Drop Python 3.10 support

- e3sm_to_cmip/__init__.py
- tbump.toml
Accidentally bumped to 0.13.0rc1 in #320 instead of 1.13.0rc1.
If applicable:
> Bump to v1.13.0rc1
